
export const testData = [
  // New York
  [
    {
      city: 'New York',
      state: 'NY',
      addressStreet1: '123 Broadway',
      addressStreet2: 'Apt 4B',
      zipcode: '10001',
      totalValuation: 750000,
      historicValueAppreciation: 5.2,
      sliderImage: ['https://example.com/ny_property1.jpg'],
      sold: 75,
      Status: 1,
    },
    {
      city: 'New York',
      state: 'NY',
      addressStreet1: '456 Park Avenue',
      addressStreet2: 'Suite 10A',
      zipcode: '10022',
      totalValuation: 1200000,
      historicValueAppreciation: 6.5,
      sliderImage: ['https://example.com/ny_property2.jpg'],
      sold: 60,
      Status: 0,
    },
  ],
  // Philadelphia
  [
    {
      city: 'Philadelphia',
      state: 'PA',
      addressStreet1: '789 Market Street',
      addressStreet2: 'Suite 202',
      zipcode: '19107',
      totalValuation: 900000,
      historicValueAppreciation: 4.8,
      sliderImage: ['https://example.com/philly_property1.jpg'],
      sold: 85,
      Status: 1,
    },
    {
      city: 'Philadelphia',
      state: 'PA',
      addressStreet1: '123 Arch Street',
      addressStreet2: 'Apt 5C',
      zipcode: '19106',
      totalValuation: 650000,
      historicValueAppreciation: 3.9,
      sliderImage: ['https://example.com/philly_property2.jpg'],
      sold: 65,
      Status: 0,
    },
  ],
  // Los Angeles
  [
    {
      city: 'Los Angeles',
      state: 'CA',
      addressStreet1: '500 Sunset Blvd',
      addressStreet2: 'Penthouse',
      zipcode: '90028',
      totalValuation: 1500000,
      historicValueAppreciation: 7.5,
      sliderImage: ['https://example.com/la_property1.jpg'],
      sold: 40,
      Status: 1,
    },
    {
      city: 'Los Angeles',
      state: 'CA',
      addressStreet1: '100 Hollywood Ave',
      addressStreet2: 'Apt 12B',
      zipcode: '90028',
      totalValuation: 950000,
      historicValueAppreciation: 6.2,
      sliderImage: ['https://example.com/la_property2.jpg'],
      sold: 70,
      Status: 0,
    },
  ],
  // Chicago
  [
    {
      city: 'Chicago',
      state: 'IL',
      addressStreet1: '200 Michigan Ave',
      addressStreet2: 'Apt 1010',
      zipcode: '60601',
      totalValuation: 800000,
      historicValueAppreciation: 4.2,
      sliderImage: ['https://example.com/chicago_property1.jpg'],
      sold: 55,
      Status: 1,
    },
    {
      city: 'Chicago',
      state: 'IL',
      addressStreet1: '250 Lakeshore Dr',
      addressStreet2: 'Suite 300',
      zipcode: '60611',
      totalValuation: 1100000,
      historicValueAppreciation: 5.3,
      sliderImage: ['https://example.com/chicago_property2.jpg'],
      sold: 45,
      Status: 0,
    },
  ],
  // Miami
  [
    {
      city: 'Miami',
      state: 'FL',
      addressStreet1: '300 Ocean Dr',
      addressStreet2: 'Apt 3A',
      zipcode: '33139',
      totalValuation: 700000,
      historicValueAppreciation: 4.0,
      sliderImage: ['https://example.com/miami_property1.jpg'],
      sold: 65,
      Status: 1,
    },
    {
      city: 'Miami',
      state: 'FL',
      addressStreet1: '150 Collins Ave',
      addressStreet2: 'Penthouse',
      zipcode: '33139',
      totalValuation: 1350000,
      historicValueAppreciation: 6.1,
      sliderImage: ['https://example.com/miami_property2.jpg'],
      sold: 50,
      Status: 0,
    },
  ],


];
